"""Inject brain hot-arcs context at session start.

Reads _hot-arcs.md from the vault NFS mount (path set by BRAIN_HOT_ARCS_PATH env var)
and injects its content into the agent's context via the standard inject_context() mechanism.

The _hot-arcs.md file is generated by the brain-keeper daemon and contains a table of the
hottest arcs currently in frontal-lobe/conscious/. Every agent session starts knowing what's
hot — what the operator is focused on, what shipped recently, what needs attention.

Enable by setting BRAIN_HOT_ARCS_PATH=/vault/frontal-lobe/conscious/_hot-arcs.md in the
agent's helm values + mounting the NFS volume.
"""
from __future__ import annotations

import os
from pathlib import Path

from hooks.common import inject_context


def inject_hot_arcs() -> None:
    """Read and inject _hot-arcs.md if available."""
    path_str = os.getenv("BRAIN_HOT_ARCS_PATH", "")
    if not path_str:
        return

    p = Path(path_str)
    if not p.exists():
        return

    try:
        content = p.read_text(encoding="utf-8").strip()
        if content:
            inject_context(f"Brain Hot Arcs (frontal-lobe/conscious):\n{content}")
    except OSError:
        pass  # NFS mount not available or file unreadable — silent skip
