#!/usr/bin/env python3
# If accidentally run with bash, re-exec with python3 (polyglot trick).
""":'
exec python3 "$0" "$@"
exit
"""

# NOTE: The triple-quoted polyglot string above becomes __doc__ in Python,
# so the real usage text is stored in _USAGE_TEXT and used as the argparse epilog.
_USAGE_TEXT = """Examples:
    agentihooks global [--profile default]
        Install hooks, skills, agents, and CLAUDE.md into ~/.claude.
        --profile selects which profile's CLAUDE.md to link (default: 'default').
        Available profiles: agentihooks --list-profiles

    agentihooks project <path> [--profile default]
        Install a profile's .mcp.json into a target project directory.

    agentihooks uninstall [--yes]
        Remove all agentihooks artifacts installed by 'agentihooks global'.

    agentihooks mcp [list|install|uninstall|sync|add] [--dir PATH]
        Manage MCP server files from ~/.agentihooks/ (or --dir).
        Drop .json files with mcpServers into the directory, then:
          agentihooks mcp              # list available MCP files
          agentihooks mcp install      # pick one to install
          agentihooks mcp uninstall    # pick one to remove
          agentihooks mcp sync         # re-apply all installed files
          agentihooks mcp add <path>   # install a file directly by path

    agentihooks ignore [path] [--force]
        Create a .claudeignore in the current directory (or given path).
        Covers secrets, build artefacts, binaries, venvs, and IDE noise.
        --force overwrites an existing file.

    agentihooks --loadenv [PATH] [-- COMMAND [ARGS...]]
        Load ~/.agentihooks/.env (or PATH) into the environment, then:
          - If COMMAND given: exec it with the loaded vars (use in aliases).
          - If no COMMAND: print 'export KEY=VALUE' lines for eval $().
        Examples:
          agentihooks --loadenv -- claude
          eval $(agentihooks --loadenv)

Re-run 'agentihooks global' after any changes to settings.base.json.
The script is idempotent.

Data directory: defaults to ~/.agentihooks/
  Override: export AGENTIHOOKS_HOME=/mnt/shared  (K8s / shared filesystem)
"""

import argparse
import json
import os
import shutil
import sys
from collections.abc import Callable
from copy import deepcopy
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

AGENTIHOOKS_ROOT = Path(__file__).resolve().parent.parent
PROFILES_DIR = AGENTIHOOKS_ROOT / "profiles"
BASE_SETTINGS = PROFILES_DIR / "_base" / "settings.base.json"


def _resolve_claude_home() -> Path:
    """Resolve the Claude config directory.

    Priority: CLAUDE_CODE_HOME_DIR > AGENTIHOOKS_CLAUDE_HOME > ~/.claude

    CLAUDE_CODE_HOME_DIR points at the home-dir root (like $HOME);
    we append .claude automatically.
    AGENTIHOOKS_CLAUDE_HOME points directly at the .claude directory (legacy).
    """
    home_dir = os.environ.get("CLAUDE_CODE_HOME_DIR")
    if home_dir:
        return Path(home_dir) / ".claude"

    claude_home = os.environ.get("AGENTIHOOKS_CLAUDE_HOME")
    if claude_home:
        return Path(claude_home)

    return Path.home() / ".claude"


CLAUDE_HOME = _resolve_claude_home()

# Persistent state directory for user-level agentihooks configuration.
AGENTIHOOKS_STATE_DIR = Path.home() / ".agentihooks"
STATE_JSON = AGENTIHOOKS_STATE_DIR / "state.json"

# Repeated path fragment constants (avoids S1192 duplicate-literal warnings)
_CLAUDE_SUBDIR = ".claude"
_CLAUDE_MD_NAME = "CLAUDE.md"
_MCP_JSON_NAME = ".mcp.json"

# Keys from ~/.claude/settings.json that belong to the user and should be
# preserved when merging (unless the base settings already define them).
PERSONAL_KEYS = {"model", "autoUpdatesChannel", "skipDangerousModePermissionPrompt"}

# Marker written into the managed settings so we can detect re-runs.
MANAGED_BY_KEY = "_managedBy"
MANAGED_BY_VALUE = "agentihooks/scripts/install.py"

# ---------------------------------------------------------------------------
# .claudeignore template
# ---------------------------------------------------------------------------

CLAUDEIGNORE_TEMPLATE = """\
# .claudeignore — files and directories Claude Code will not read or index.
# Generated by: agentihooks ignore
# Syntax: same as .gitignore (glob patterns, one per line).

# ── Credentials & secrets ──────────────────────────────────────────────────
.env
.env.*
!.env.example
*.pem
*.key
*.p12
*.pfx
*.jks
*.keystore
secrets/
credentials/
.secrets/

# ── Build artefacts ────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.pyo
.mypy_cache/
.ruff_cache/
.pytest_cache/
dist/
build/
*.egg-info/
.eggs/
node_modules/
.next/
.nuxt/
out/
target/           # Rust / Java
*.class

# ── Runtime & generated data ───────────────────────────────────────────────
*.log
*.log.*
logs/
*.sqlite
*.sqlite3
*.db
*.lock             # e.g. poetry.lock, package-lock.json — often huge
!pyproject.toml    # keep build manifests readable

# ── Test coverage & reports ────────────────────────────────────────────────
.coverage
htmlcov/
coverage.xml
*.lcov
junit*.xml

# ── IDE & OS noise ─────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo
.DS_Store
Thumbs.db

# ── Large binary / media ───────────────────────────────────────────────────
*.zip
*.tar.gz
*.tgz
*.tar.bz2
*.gz
*.rar
*.7z
*.iso
*.dmg
*.pdf
*.png
*.jpg
*.jpeg
*.gif
*.svg
*.ico
*.mp4
*.mp3
*.wav
*.woff
*.woff2
*.ttf
*.eot

# ── Virtual environments ───────────────────────────────────────────────────
.venv/
venv/
env/
.env/

# ── Terraform / Ansible ────────────────────────────────────────────────────
.terraform/
*.tfstate
*.tfstate.backup
.terraform.lock.hcl
"""


# ---------------------------------------------------------------------------
# JSON helpers
# ---------------------------------------------------------------------------


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge *override* into *base* (override wins)."""
    merged = deepcopy(base)
    for key, value in override.items():
        if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = deepcopy(value)
    return merged


# ---------------------------------------------------------------------------
# State helpers (~/.agentihooks/state.json)
# ---------------------------------------------------------------------------


def _load_state() -> dict:
    if STATE_JSON.exists():
        try:
            return load_json(STATE_JSON)
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _save_state(state: dict) -> None:
    AGENTIHOOKS_STATE_DIR.mkdir(parents=True, exist_ok=True)
    save_json(STATE_JSON, state)


def _state_add_mcp(mcp_path: Path) -> None:
    """Record *mcp_path* in state.json so --sync can restore it."""
    state = _load_state()
    paths: list[str] = state.get("mcpFiles", [])
    path_str = str(mcp_path)
    if path_str not in paths:
        paths.append(path_str)
        state["mcpFiles"] = paths
        _save_state(state)


def _state_set_mcp_lib(path: Path) -> None:
    """Persist the MCP library directory in state.json."""
    state = _load_state()
    state["mcpLibPath"] = str(path)
    _save_state(state)


def _state_get_mcp_lib() -> Path | None:
    """Return the saved MCP library directory, or None if not set."""
    val = _load_state().get("mcpLibPath")
    return Path(val) if val else None


def _state_remove_mcp(mcp_path: Path) -> None:
    """Remove *mcp_path* from state.json."""
    state = _load_state()
    paths: list[str] = state.get("mcpFiles", [])
    path_str = str(mcp_path)
    if path_str in paths:
        paths.remove(path_str)
        state["mcpFiles"] = paths
        _save_state(state)


# ---------------------------------------------------------------------------
# User env file (~/.agentihooks/.env)
# ---------------------------------------------------------------------------

_ENV_FILE_DST = AGENTIHOOKS_STATE_DIR / ".env"
_ENV_EXAMPLE_SRC = AGENTIHOOKS_ROOT / ".env.example"


def _seed_user_env_file() -> None:
    """Create ~/.agentihooks/.env from .env.example if it doesn't already exist.

    Never overwrites — only creates on first install.
    The user is the only one who should delete or modify this file.
    """
    AGENTIHOOKS_STATE_DIR.mkdir(parents=True, exist_ok=True)
    if _ENV_FILE_DST.exists():
        print(f"  [--] {_ENV_FILE_DST} already exists — not overwritten (your file)")
        return
    if _ENV_EXAMPLE_SRC.exists():
        shutil.copy2(_ENV_EXAMPLE_SRC, _ENV_FILE_DST)
        print(f"  [OK] Created {_ENV_FILE_DST}")
        print(f"       Configure your integrations: {_ENV_FILE_DST}")
    else:
        print(f"  [!!] .env.example not found — could not seed {_ENV_FILE_DST}")


# ---------------------------------------------------------------------------
# --loadenv: install agentihooksenv alias into ~/.bashrc (managed block)
# ---------------------------------------------------------------------------

_BASHRC = Path.home() / ".bashrc"
_BLOCK_START = "# === agentihooks ==="
_BLOCK_END = "# === end-agentihooks ==="


def _cmd_loadenv(env_file: Path, exec_cmd: list[str], *, force: bool = False) -> None:
    """Write a managed alias block into ~/.bashrc so `agentienv` sources the .env."""
    if not env_file.is_file():
        print(f"[!!] env file not found: {env_file}", file=sys.stderr)
        sys.exit(1)

    env_dir = env_file.parent
    block = (
        f"{_BLOCK_START}\n"
        f"agentienv() {{\n"
        f"  if [ ! -f \"{env_file}\" ]; then\n"
        f"    echo \"[agentienv] no .env found at {env_file} — skipping\"\n"
        f"    return 0\n"
        f"  fi\n"
        f"  set -a\n"
        f"  . \"{env_file}\" 2>/dev/null || {{ echo \"[agentienv] ERROR: failed to source {env_file}\"; set +a; return 1; }}\n"
        f"  _aih_count=1\n"
        f"  for f in \"{env_dir}\"/*.env; do\n"
        f"    [ -f \"$f\" ] && [ \"$f\" != \"{env_file}\" ] && {{\n"
        f"      . \"$f\" 2>/dev/null || echo \"[agentienv] WARNING: failed to source $f\"\n"
        f"      _aih_count=$((_aih_count + 1))\n"
        f"    }}\n"
        f"  done\n"
        f"  set +a\n"
        f"  echo \"[agentienv] loaded $_aih_count env file(s) from {env_dir}\"\n"
        f"}}\n"
        f"agentienv\n"
        f"{_BLOCK_END}\n"
    )

    bashrc_text = _BASHRC.read_text(encoding="utf-8") if _BASHRC.exists() else ""

    if _BLOCK_START in bashrc_text:
        # Replace existing block
        lines = bashrc_text.splitlines(keepends=True)
        new_lines = []
        inside = False
        for line in lines:
            if line.rstrip() == _BLOCK_START:
                inside = True
                new_lines.append(block)
            elif line.rstrip() == _BLOCK_END:
                inside = False
            elif not inside:
                new_lines.append(line)
        _BASHRC.write_text("".join(new_lines), encoding="utf-8")
        print(f"[OK] Updated agentihooks block in {_BASHRC}")
    else:
        # Append new block
        sep = "\n" if bashrc_text and not bashrc_text.endswith("\n") else ""
        _BASHRC.write_text(bashrc_text + sep + block, encoding="utf-8")
        print(f"[OK] Added agentihooks block to {_BASHRC}")

    print()
    print("Now reload your shell and use:")
    print("  source ~/.bashrc")
    print("  agentienv")
    print()

    _prompt_install_requirements(force=force)


def _find_requirements_files() -> list[Path]:
    """Return requirements.txt files found in ~/.agentihooks/ and mcpLibPath."""
    candidates: list[Path] = []
    for search_dir in [AGENTIHOOKS_STATE_DIR, _state_get_mcp_lib()]:
        if search_dir is None:
            continue
        req = search_dir / "requirements.txt"
        if req.is_file() and req not in candidates:
            candidates.append(req)
    return candidates


def _detect_venv() -> Path | None:
    """Return the Python executable inside the active or local venv, or None.

    ~/.agentihooks/.venv always wins when it exists — it is the canonical
    environment regardless of which project venv happens to be activated.
    """
    # 1. Dedicated ~/.agentihooks/.venv — always preferred when present
    agentihooks_venv = Path.home() / ".agentihooks" / ".venv" / "bin" / "python"
    if agentihooks_venv.exists():
        return agentihooks_venv

    # 2. Activated venv via VIRTUAL_ENV (fallback if dedicated venv missing)
    venv_env = os.environ.get("VIRTUAL_ENV")
    if venv_env:
        python = Path(venv_env) / "bin" / "python"
        if python.exists():
            return python

    # 3. .venv directory in cwd
    local_venv = Path.cwd() / ".venv" / "bin" / "python"
    if local_venv.exists():
        return local_venv

    return None


def _prompt_install_requirements(*, force: bool = False) -> None:
    """Discover requirements.txt files and offer to install each with uv.

    *force* skips venv detection and installs into system Python (for Docker/CI).
    """
    import subprocess

    req_files = _find_requirements_files()
    if not req_files:
        return

    uv = shutil.which("uv")
    if not uv:
        print("  [!!] uv not found — skipping requirements install.")
        return

    for req in req_files:
        try:
            answer = input(f"Found {req} — install with uv? [y/N] ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nSkipped.")
            return

        if answer != "y":
            print("  [--] Skipped.")
            continue

        if force:
            python = Path(sys.executable)
            print(f"  [..] Installing into system Python ({python}) ...")
        else:
            python = _detect_venv()
            if python is None:
                print("  [!!] No virtual environment found.")
                print("       Create and activate one first:")
                print("         python3 -m venv .venv && source .venv/bin/activate")
                print(
                    "       Or use --force to install into system Python (Docker/CI)."
                )
                print("       Then re-run: agentihooks --loadenv")
                continue
            print(f"  [..] Installing into {python.parent.parent} ...")
        result = subprocess.run(
            [uv, "pip", "install", "--python", str(python), "-r", str(req)],
            capture_output=False,
        )
        if result.returncode == 0:
            print(f"  [OK] Installed {req}")
        else:
            print(f"  [!!] uv pip install failed (exit {result.returncode})")


# ---------------------------------------------------------------------------
# Path substitution: replace /app with the actual agentihooks root
# ---------------------------------------------------------------------------


def substitute_paths(
    obj: object, src: str = "/app", dst: str = str(AGENTIHOOKS_ROOT)
) -> object:
    """Recursively replace *src* with *dst* in all string values of a JSON structure."""
    if isinstance(obj, str):
        return obj.replace(src, dst)
    if isinstance(obj, dict):
        return {k: substitute_paths(v, src, dst) for k, v in obj.items()}
    if isinstance(obj, list):
        return [substitute_paths(item, src, dst) for item in obj]
    return obj


def _available_profiles() -> list[str]:
    """Return profile names (dirs under profiles/ excluding _base)."""
    return sorted(
        d.name
        for d in PROFILES_DIR.iterdir()
        if d.is_dir() and not d.name.startswith("_")
    )


def _read_profile_field(profile_dir: Path, field: str) -> str:
    """Read a top-level field from profile.yml (simple key: value only)."""
    yml = profile_dir / "profile.yml"
    if not yml.exists():
        return ""
    prefix = f"{field}:"
    for line in yml.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith(prefix):
            return stripped[len(prefix) :].strip().strip('"').strip("'")
    return ""


def _read_profile_description(profile_dir: Path) -> str:
    """Return the description field from profile.yml, or '' if absent."""
    return _read_profile_field(profile_dir, "description")


def query_active_profile() -> None:
    """Print the currently installed global profile and exit."""
    claude_md = CLAUDE_HOME / _CLAUDE_MD_NAME
    if not claude_md.exists():
        print("not installed")
        return
    if not claude_md.is_symlink():
        print("unmanaged  (CLAUDE.md is not a symlink — installed manually)")
        return
    target = claude_md.resolve()
    try:
        # Expect: <root>/profiles/<name>/.claude/CLAUDE.md
        rel = target.relative_to(PROFILES_DIR)
        profile_name = rel.parts[0]
        print(profile_name)
    except ValueError:
        print(f"unknown  (symlink points outside profiles/: {target})")


def list_profiles() -> None:
    """Print all available profiles and exit."""
    profiles = _available_profiles()
    if not profiles:
        print("No profiles found in profiles/ (only _base exists).")
        return
    print(f"Available profiles ({PROFILES_DIR}):\n")
    for name in profiles:
        desc = _read_profile_description(PROFILES_DIR / name)
        marker = ""
        claude_md = PROFILES_DIR / name / _CLAUDE_SUBDIR / _CLAUDE_MD_NAME
        if not claude_md.exists():
            marker = f"  [no {_CLAUDE_MD_NAME}]"
        desc_str = f"  — {desc}" if desc else ""
        print(f"  {name}{desc_str}{marker}")
    print()


# ---------------------------------------------------------------------------
# Settings helpers
# ---------------------------------------------------------------------------


def _preserve_personal_keys(existing_path: Path) -> dict:
    """Return personal keys from an existing unmanaged settings file."""
    personal: dict = {}
    if not existing_path.exists():
        return personal
    try:
        existing = load_json(existing_path)
        if existing.get(MANAGED_BY_KEY) == MANAGED_BY_VALUE:
            return personal  # Already managed — don't re-import
        for key in PERSONAL_KEYS:
            if key in existing:
                personal[key] = existing[key]
        if personal:
            print(
                f"Preserving personal keys from existing settings: {sorted(personal)}"
            )
    except json.JSONDecodeError:
        print(
            "WARNING: existing settings.json is invalid JSON – skipping preservation."
        )
    return personal


def _backup_settings(existing_path: Path) -> None:
    """Back up an existing unmanaged settings file (skips if already managed)."""
    if not existing_path.exists():
        return
    existing_raw = load_json(existing_path)
    if existing_raw.get(MANAGED_BY_KEY) == MANAGED_BY_VALUE:
        return
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = existing_path.with_suffix(f".json.bak.{timestamp}")
    shutil.copy2(existing_path, backup_path)
    print(f"Backed up existing settings → {backup_path}")


# ---------------------------------------------------------------------------
# Global install
# ---------------------------------------------------------------------------


def install_global(args: argparse.Namespace) -> None:
    profile_name: str = args.profile

    # Validate profile exists
    profile_dir = PROFILES_DIR / profile_name
    if not profile_dir.is_dir():
        available = _available_profiles()
        print(f"ERROR: Profile '{profile_name}' not found.", file=sys.stderr)
        print(f"Available profiles: {', '.join(available)}", file=sys.stderr)
        sys.exit(1)

    print(f"agentihooks root : {AGENTIHOOKS_ROOT}")
    print(f"Target           : {CLAUDE_HOME}")
    print(f"Profile          : {profile_name}")
    # Resolve canonical Python: ~/.agentihooks/.venv wins over sys.executable
    # so that `agentihooks global` (run via uv tool from any project venv) always
    # bakes the right path into hook commands.
    _canonical_python = str(_detect_venv() or sys.executable)
    print(f"Python           : {_canonical_python}")
    print()

    # --- 1. Load and render base settings ---
    if not BASE_SETTINGS.exists():
        print(f"ERROR: {BASE_SETTINGS} not found.", file=sys.stderr)
        sys.exit(1)

    raw_settings = load_json(BASE_SETTINGS)
    rendered: dict = substitute_paths(
        raw_settings
    )  # NOSONAR — intentional object→dict cast
    rendered = substitute_paths(rendered, "__PYTHON__", _canonical_python)  # NOSONAR

    # --- 1b. Apply per-profile overrides (e.g. env vars like AGENTIHOOKS_SECRETS_MODE) ---
    overrides_path = PROFILES_DIR / profile_name / "settings.overrides.json"
    if overrides_path.exists():
        overrides = load_json(overrides_path)
        rendered = _deep_merge(rendered, overrides)
        print(f"Applied profile overrides: {overrides_path}")

    # --- 2. Merge personal keys from existing settings ---
    existing_settings_path = CLAUDE_HOME / "settings.json"
    personal = _preserve_personal_keys(existing_settings_path)
    merged: dict = deepcopy(personal)
    merged.update(rendered)
    merged[MANAGED_BY_KEY] = MANAGED_BY_VALUE

    # --- 3. Backup + write ---
    _backup_settings(existing_settings_path)
    CLAUDE_HOME.mkdir(parents=True, exist_ok=True)
    save_json(existing_settings_path, merged)
    print(f"[OK] Wrote {existing_settings_path}")

    # --- 4. Symlink skills (directories only) ---
    _symlink_dir_contents(
        AGENTIHOOKS_ROOT / _CLAUDE_SUBDIR / "skills",
        CLAUDE_HOME / "skills",
        label="skill",
        filter_fn=lambda p: p.is_dir(),
    )

    # --- 5. Symlink agents (.md files only, excluding README.md) ---
    _symlink_dir_contents(
        AGENTIHOOKS_ROOT / _CLAUDE_SUBDIR / "agents",
        CLAUDE_HOME / "agents",
        label="agent",
        filter_fn=lambda p: p.suffix == ".md" and p.name != "README.md",
    )

    # --- 6. Symlink commands (.md files only, excluding README.md) ---
    _symlink_dir_contents(
        AGENTIHOOKS_ROOT / _CLAUDE_SUBDIR / "commands",
        CLAUDE_HOME / "commands",
        label="command",
        filter_fn=lambda p: p.suffix == ".md" and p.name != "README.md",
    )

    # --- 7. Symlink CLAUDE.md from the chosen profile ---
    profile_claude_md = PROFILES_DIR / profile_name / _CLAUDE_SUBDIR / _CLAUDE_MD_NAME
    claude_md_dst = CLAUDE_HOME / _CLAUDE_MD_NAME
    _install_claude_md(profile_claude_md, claude_md_dst, profile_name)

    # --- 8. Install profile MCP servers to user scope (~/.claude.json) ---
    _install_user_mcp(profile_name)

    # --- 9. Re-apply any custom MCPs tracked in state.json ---
    if STATE_JSON.exists():
        print()
        sync_user_mcp()

    # --- 9b. Auto-install MCP file from AGENTIHOOKS_MCP_FILE env var ---
    mcp_file_env = os.environ.get("AGENTIHOOKS_MCP_FILE", "")
    if mcp_file_env:
        mcp_path = Path(mcp_file_env).expanduser().resolve()
        if mcp_path.exists():
            print()
            manage_user_mcp(mcp_path)
        else:
            print(f"  [--] AGENTIHOOKS_MCP_FILE={mcp_file_env} not found — skipping.")

    # --- 10. Install agentihooks CLI tool to ~/.local/bin ---
    print()
    _install_cli_tool()

    # --- 11. Seed ~/.agentihooks/.env from .env.example (first run only) ---
    print()
    _seed_user_env_file()

    # --- Done ---
    print()
    print("Installation complete.")
    print()
    print("Verification steps:")
    print(f"  ls -la {existing_settings_path}")
    print(f"  ls -la {claude_md_dst}")
    print("  Open Claude Code in any project → run /status (hooks should be active)")
    print("  Run /skills to list installed skills")
    print()
    print("To update after settings.base.json changes:")
    print("  agentihooks global")
    print()
    print("Shell tip: wrap Claude Code to load MCP keys from ~/.agentihooks/.env:")
    print("  alias cc='agentihooks --loadenv -- claude'")
    print("  Or for eval mode: eval $(agentihooks --loadenv)")


# ---------------------------------------------------------------------------
# User-scope MCP install (~/.claude.json)
# ---------------------------------------------------------------------------


def _resolve_claude_json() -> Path:
    """Resolve ~/.claude.json, respecting CLAUDE_CODE_HOME_DIR."""
    home_dir = os.environ.get("CLAUDE_CODE_HOME_DIR")
    if home_dir:
        return Path(home_dir) / ".claude.json"
    return Path.home() / ".claude.json"


_CLAUDE_JSON = _resolve_claude_json()


def _merge_mcp_to_user_scope(servers: dict) -> None:
    """Merge *servers* into the top-level mcpServers of ~/.claude.json."""
    existing: dict = load_json(_CLAUDE_JSON) if _CLAUDE_JSON.exists() else {}
    existing_servers: dict = existing.get("mcpServers", {})
    added, updated = [], []
    for name, config in servers.items():
        if name in existing_servers:
            if existing_servers[name] != config:
                updated.append(name)
        else:
            added.append(name)
        existing_servers[name] = config
    existing["mcpServers"] = existing_servers
    save_json(_CLAUDE_JSON, existing)
    if added:
        print(f"  [OK] Added user-scope MCP servers  : {', '.join(added)}")
    if updated:
        print(f"  [OK] Updated user-scope MCP servers: {', '.join(updated)}")
    if not added and not updated:
        print(f"  [--] User-scope MCP servers unchanged: {', '.join(servers.keys())}")


def _remove_mcp_from_user_scope(servers: dict) -> None:
    """Remove *servers* keys from the top-level mcpServers of ~/.claude.json."""
    if not _CLAUDE_JSON.exists():
        print("  [--] ~/.claude.json does not exist — nothing to remove.")
        return
    existing: dict = load_json(_CLAUDE_JSON)
    existing_servers: dict = existing.get("mcpServers", {})
    removed, missing = [], []
    for name in servers:
        if name in existing_servers:
            del existing_servers[name]
            removed.append(name)
        else:
            missing.append(name)
    existing["mcpServers"] = existing_servers
    save_json(_CLAUDE_JSON, existing)
    if removed:
        print(f"  [OK] Removed user-scope MCP servers: {', '.join(removed)}")
    if missing:
        print(f"  [--] Not found (already removed?)  : {', '.join(missing)}")


def _build_mcp_config(mcp_categories: str) -> dict:
    """Build MCP server config for the hooks-utils server."""
    return {
        "mcpServers": {
            "hooks-utils": {
                "command": sys.executable,
                "args": ["-m", "hooks.mcp"],
                "cwd": str(AGENTIHOOKS_ROOT),
                "env": {"MCP_CATEGORIES": mcp_categories},
            }
        }
    }


def _install_user_mcp(profile_name: str) -> None:
    """Generate and merge MCP server config into ~/.claude.json.

    Reads ``mcp_categories`` from ``profile.yml`` (defaults to ``all``)
    and builds the hooks-utils MCP server config dynamically.
    """
    profile_dir = PROFILES_DIR / profile_name
    mcp_categories = _read_profile_field(profile_dir, "mcp_categories") or "all"
    mcp_config = _build_mcp_config(mcp_categories)
    _merge_mcp_to_user_scope(mcp_config["mcpServers"])


def manage_user_mcp(mcp_path: Path, *, uninstall: bool = False) -> None:
    """Install or uninstall MCP servers from an external file into user scope.

    Reads *mcp_path* (must contain a ``mcpServers`` dict) and either merges
    all servers into ``~/.claude.json`` (install) or removes them (uninstall).
    No path substitution is applied — the file is used as-is.
    """
    if not mcp_path.exists():
        print(f"ERROR: MCP file not found: {mcp_path}", file=sys.stderr)
        sys.exit(1)
    try:
        raw = load_json(mcp_path)
    except (json.JSONDecodeError, OSError) as exc:
        print(f"ERROR: Cannot read {mcp_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    servers: dict = raw.get("mcpServers", {})
    if not servers:
        print(f"  [--] No mcpServers found in {mcp_path} — nothing to do.")
        return

    action = "Uninstalling" if uninstall else "Installing"
    print(f"{action} MCP servers from {mcp_path}:")
    print(f"  Servers: {', '.join(servers.keys())}")
    print()
    if uninstall:
        _remove_mcp_from_user_scope(servers)
        _state_remove_mcp(mcp_path)
    else:
        _merge_mcp_to_user_scope(servers)
        _state_add_mcp(mcp_path)


def sync_user_mcp() -> None:
    """Re-apply all MCP files tracked in ~/.agentihooks/state.json.

    Skips paths that no longer exist (with a warning) so a missing
    repo doesn't abort the whole sync.
    """
    state = _load_state()
    paths: list[str] = state.get("mcpFiles", [])
    if not paths:
        print(f"  [--] No MCP files tracked in {STATE_JSON} — nothing to sync.")
        return

    print(f"Syncing {len(paths)} tracked MCP file(s) from {STATE_JSON}:")
    for path_str in paths:
        p = Path(path_str)
        if not p.exists():
            print(f"  [!!] Skipping missing file: {path_str}")
            continue
        try:
            raw = load_json(p)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"  [!!] Cannot read {path_str}: {exc}")
            continue
        servers: dict = raw.get("mcpServers", {})
        if not servers:
            print(f"  [--] No mcpServers in {path_str} — skipping.")
            continue
        print(f"  From {p.name}: {', '.join(servers.keys())}")
        _merge_mcp_to_user_scope(servers)


# ---------------------------------------------------------------------------
# Interactive MCP uninstall (--mcp --uninstall without a path)
# ---------------------------------------------------------------------------


def _cmd_mcp_interactive_uninstall() -> None:
    """Show tracked MCP files, let user pick one, uninstall its servers."""
    state = _load_state()
    paths: list[str] = state.get("mcpFiles", [])

    if not paths:
        print(f"No MCP files tracked in {STATE_JSON} — nothing to uninstall.")
        return

    print("Tracked MCP files:\n")
    for i, path_str in enumerate(paths, 1):
        p = Path(path_str)
        if not p.exists():
            print(f"  {i}. {path_str}  [file not found]")
            continue
        try:
            servers = load_json(p).get("mcpServers", {})
            names = ", ".join(servers.keys()) if servers else "(no servers)"
            print(f"  {i}. {path_str}")
            print(f"     {len(servers)} server(s): {names}")
        except (json.JSONDecodeError, OSError):
            print(f"  {i}. {path_str}  [unreadable]")

    print()
    try:
        raw = input(
            f"Select file to uninstall [1-{len(paths)}] (or q to quit): "
        ).strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(0)

    if raw.lower() == "q":
        print("Aborted.")
        sys.exit(0)

    try:
        idx = int(raw) - 1
        if not 0 <= idx < len(paths):
            raise ValueError
    except ValueError:
        print("Invalid selection.")
        sys.exit(1)

    selected = Path(paths[idx])
    print()
    manage_user_mcp(selected, uninstall=True)
    print()
    print("Restart Claude Code for the changes to take effect.")


# ---------------------------------------------------------------------------
# --mcp-lib: browse a directory of .mcp.json files and install one
# ---------------------------------------------------------------------------


def _cmd_mcp_lib(lib_path: Path | None) -> None:
    """Scan a directory for .mcp.json files and interactively install one."""
    if lib_path is None:
        lib_path = _state_get_mcp_lib()
        if lib_path is None:
            print("No MCP library path set. Provide one:")
            print("  agentihooks --mcp-lib /path/to/dir")
            sys.exit(1)
        print(f"Using saved MCP library: {lib_path}")

    lib_path = lib_path.expanduser().resolve()
    if not lib_path.is_dir():
        print(f"[!!] Not a directory: {lib_path}", file=sys.stderr)
        sys.exit(1)

    # Keep only files that contain mcpServers
    mcp_files: list[tuple[Path, dict]] = []
    for f in sorted(lib_path.glob("*.json")):
        try:
            data = load_json(f)
            if "mcpServers" in data:
                mcp_files.append((f, data["mcpServers"]))
        except (json.JSONDecodeError, OSError):
            pass

    if not mcp_files:
        print(f"No .json files with mcpServers found in {lib_path}")
        sys.exit(0)

    # Save path for future --mcp-lib calls
    _state_set_mcp_lib(lib_path)

    already_tracked = set(_load_state().get("mcpFiles", []))

    print(f"MCP files in {lib_path}:\n")
    for i, (f, servers) in enumerate(mcp_files, 1):
        names = ", ".join(servers.keys())
        tracked = "  [installed]" if str(f) in already_tracked else ""
        print(f"  {i}. {f.name}{tracked}")
        print(f"     {len(servers)} server(s): {names}")

    print()
    try:
        raw = input(
            f"Select file to install [1-{len(mcp_files)}] (or q to quit): "
        ).strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        sys.exit(0)

    if raw.lower() == "q":
        print("Aborted.")
        sys.exit(0)

    try:
        idx = int(raw) - 1
        if not 0 <= idx < len(mcp_files):
            raise ValueError
    except ValueError:
        print("Invalid selection.")
        sys.exit(1)

    selected, _ = mcp_files[idx]
    print()
    manage_user_mcp(selected)
    print()
    print("Restart Claude Code for the changes to take effect.")


# ---------------------------------------------------------------------------
# CLI tool install (uv tool install --editable .)
# ---------------------------------------------------------------------------

_CLI_NAME = "agentihooks"


def _install_cli_tool() -> None:
    """Install the agentihooks CLI globally via ``uv tool install --editable .``."""
    import subprocess

    uv = shutil.which("uv")
    if not uv:
        print(
            "  [!!] uv not found — install uv first: https://docs.astral.sh/uv/getting-started/installation/"
        )
        print("       Then re-run: uv run agentihooks global")
        return

    result = subprocess.run(
        [uv, "tool", "install", "--editable", "--force", "."],
        cwd=AGENTIHOOKS_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print("  [OK] CLI installed via: uv tool install --editable .")
    else:
        print(f"  [!!] uv tool install failed: {result.stderr.strip()}")


def _uninstall_cli_tool() -> None:
    """Uninstall the agentihooks CLI via ``uv tool uninstall``."""
    import subprocess

    uv = shutil.which("uv")
    if not uv:
        print("  [!!] uv not found — cannot uninstall CLI automatically.")
        print(f"       Remove manually: uv tool uninstall {_CLI_NAME}")
        return

    result = subprocess.run(
        [uv, "tool", "uninstall", _CLI_NAME],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print(f"  [OK] Uninstalled CLI via: uv tool uninstall {_CLI_NAME}")
    else:
        stderr = result.stderr.strip()
        if "not installed" in stderr.lower():
            print(f"  [--] {_CLI_NAME} was not installed via uv tool (skipping)")
        else:
            print(f"  [!!] uv tool uninstall failed: {stderr}")


# ---------------------------------------------------------------------------
# Symlink helpers
# ---------------------------------------------------------------------------


def _remove_agentihooks_symlinks(dst_dir: Path, label: str) -> int:
    """Remove symlinks in *dst_dir* whose resolved target is inside AGENTIHOOKS_ROOT.

    Returns the count of removed links. Non-symlinks and symlinks pointing
    elsewhere are left untouched (user-created links stay safe).
    """
    if not dst_dir.exists():
        return 0
    count = 0
    root_str = str(AGENTIHOOKS_ROOT)
    for link in sorted(dst_dir.iterdir()):
        if not link.is_symlink():
            continue
        try:
            target = link.resolve()
        except OSError:
            continue
        if str(target).startswith(root_str):
            link.unlink()
            print(f"  [RM] Removed {label} symlink: {link.name}")
            count += 1
    return count


def _cleanup_stale_links(
    dst_dir: Path, src_dir: Path, filter_fn: Callable[[Path], bool] | None
) -> None:
    """Remove broken symlinks and symlinks that no longer pass *filter_fn*."""
    if not dst_dir.exists():
        return
    for link in sorted(dst_dir.iterdir()):
        if not link.is_symlink():
            continue
        target = link.resolve()
        if not link.exists():
            link.unlink()
            print(f"  [RM] Removed broken symlink: {link.name}")
        elif (
            target.parent.resolve() == src_dir.resolve()
            and filter_fn
            and not filter_fn(target)
        ):
            link.unlink()
            print(f"  [RM] Removed stale symlink: {link.name}")


def _link_item(item: Path, link: Path, label: str) -> None:
    """Create or update a single symlink *link* → *item*."""
    if link.is_symlink():
        if link.resolve() == item.resolve():
            print(f"  [--] {label} '{item.name}' already linked → {item}")
        else:
            link.unlink()
            link.symlink_to(item)
            print(f"  [OK] Re-linked {label} '{item.name}' → {item}")
    elif link.exists():
        print(
            f"  [!!] {label} '{item.name}' exists at {link} and is not a symlink – skipping (remove manually)"
        )
    else:
        link.symlink_to(item)
        print(f"  [OK] Linked {label} '{item.name}' → {item}")


def _symlink_dir_contents(
    src_dir: Path,
    dst_dir: Path,
    *,
    label: str,
    filter_fn: Callable[[Path], bool] | None = None,
) -> None:
    """Symlink filtered children of *src_dir* into *dst_dir*.

    Stale symlinks (broken or pointing to items that no longer pass the filter)
    are removed automatically before new links are created.
    """
    if not src_dir.exists():
        print(f"  (no {label}s directory at {src_dir}, skipping)")
        return

    _cleanup_stale_links(dst_dir, src_dir, filter_fn)

    children = [c for c in src_dir.iterdir() if not filter_fn or filter_fn(c)]
    if not children:
        print(f"  (no valid {label}s found in {src_dir} after filtering, skipping)")
        return

    dst_dir.mkdir(parents=True, exist_ok=True)
    for item in sorted(children):
        if not item.name.startswith("."):
            _link_item(item, dst_dir / item.name, label)


def _install_claude_md(src: Path, dst: Path, profile_name: str) -> None:
    """Symlink *dst* (~/.claude/CLAUDE.md) → *src* (profile CLAUDE.md)."""
    if not src.exists():
        print(f"  [!!] Profile {_CLAUDE_MD_NAME} not found at {src} — skipping.")
        print(f"       Available profiles: {_available_profiles()}")
        return

    if dst.is_symlink():
        if dst.resolve() == src.resolve():
            print(f"  [--] {_CLAUDE_MD_NAME} already linked → {src}")
        else:
            dst.unlink()
            dst.symlink_to(src)
            print(f"  [OK] Re-linked {_CLAUDE_MD_NAME} → {src}")
        return

    if dst.exists():
        print(f"\nA {_CLAUDE_MD_NAME} already exists at {dst}.")
        answer = (
            input(
                f"Replace with symlink to profiles/{profile_name}/{_CLAUDE_SUBDIR}/{_CLAUDE_MD_NAME}? [y/N] "
            )
            .strip()
            .lower()
        )
        if answer == "y":
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup = dst.with_suffix(f".md.bak.{timestamp}")
            shutil.copy2(dst, backup)
            print(f"  Backed up existing {_CLAUDE_MD_NAME} → {backup}")
            dst.unlink()
            dst.symlink_to(src)
            print(f"  [OK] Linked {_CLAUDE_MD_NAME} → {src}")
        else:
            print(f"  [--] Skipped {_CLAUDE_MD_NAME} linking.")
        return

    dst.symlink_to(src)
    print(f"  [OK] Linked {_CLAUDE_MD_NAME} → {src}")


# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------


def _collect_all_managed_mcp_servers() -> dict:
    """Return the union of all MCP servers managed by agentihooks.

    Collects servers from:
    1. The hooks-utils server (generated from profile mcp_categories)
    2. All files tracked in ~/.agentihooks/state.json mcpFiles

    Returns a merged {name: config} dict.
    """
    merged: dict = {}

    # --- hooks-utils server (always present, categories don't matter for uninstall) ---
    mcp_config = _build_mcp_config("all")
    merged.update(mcp_config["mcpServers"])

    # --- State-tracked MCP files ---
    state = _load_state()
    for path_str in state.get("mcpFiles", []):
        p = Path(path_str)
        if not p.exists():
            continue
        try:
            raw = load_json(p)
            for name, cfg in raw.get("mcpServers", {}).items():
                merged[name] = cfg
        except (json.JSONDecodeError, OSError):
            pass

    return merged


def uninstall_global(args: argparse.Namespace) -> None:
    """Remove all agentihooks artifacts installed by 'install global'."""
    yes: bool = args.yes

    settings_path = CLAUDE_HOME / "settings.json"
    skills_dir = CLAUDE_HOME / "skills"
    agents_dir = CLAUDE_HOME / "agents"
    commands_dir = CLAUDE_HOME / "commands"
    claude_md_dst = CLAUDE_HOME / _CLAUDE_MD_NAME

    # --- Audit ---
    remove_settings = False
    if settings_path.exists():
        try:
            remove_settings = (
                load_json(settings_path).get(MANAGED_BY_KEY) == MANAGED_BY_VALUE
            )
        except (json.JSONDecodeError, OSError):
            pass

    def _count_agentihooks_symlinks(d: Path) -> int:
        if not d.exists():
            return 0
        root_str = str(AGENTIHOOKS_ROOT)
        return sum(
            1
            for lnk in d.iterdir()
            if lnk.is_symlink() and str(lnk.resolve()).startswith(root_str)
        )

    n_skills = _count_agentihooks_symlinks(skills_dir)
    n_agents = _count_agentihooks_symlinks(agents_dir)
    n_commands = _count_agentihooks_symlinks(commands_dir)

    remove_claude_md = claude_md_dst.is_symlink() and str(
        claude_md_dst.resolve()
    ).startswith(str(PROFILES_DIR))

    managed_servers = _collect_all_managed_mcp_servers()

    # --- Summary ---
    print("agentihooks uninstall")
    print("======================")
    print("Will remove:")
    if remove_settings:
        print(f"  {settings_path}  (managed by agentihooks)")
    else:
        print(f"  {settings_path}  [SKIP — not managed or not found]")
    print(f"  {skills_dir}/  → {n_skills} symlink(s)")
    print(f"  {agents_dir}/  → {n_agents} symlink(s)")
    print(f"  {commands_dir}/  → {n_commands} symlink(s)")
    if remove_claude_md:
        print(f"  {claude_md_dst}  (symlink → profiles/)")
    else:
        print(f"  {claude_md_dst}  [SKIP — not a managed symlink]")
    if managed_servers:
        print(
            f"  MCP servers from {_CLAUDE_JSON}: {', '.join(sorted(managed_servers.keys()))}"
        )
    else:
        print(f"  MCP servers from {_CLAUDE_JSON}: [none found]")
    print("  agentihooks CLI (uv tool / symlink)")
    print()
    print(f"NOT removed (your data): {STATE_JSON}")
    print()

    if not yes:
        answer = input("Proceed? [y/N] ").strip().lower()
        if answer != "y":
            print("Aborted.")
            sys.exit(0)

    # --- 3. Remove settings.json ---
    if remove_settings:
        settings_path.unlink()
        print(f"[OK] Removed {settings_path}")
    else:
        print(f"[--] Skipped {settings_path} (not managed)")

    # --- 4. Remove symlinks in skills, agents, commands ---
    print()
    for dst_dir, label in [
        (skills_dir, "skill"),
        (agents_dir, "agent"),
        (commands_dir, "command"),
    ]:
        n = _remove_agentihooks_symlinks(dst_dir, label)
        if n == 0:
            print(f"  [--] No {label} symlinks found in {dst_dir}")

    # --- 5. Remove CLAUDE.md symlink ---
    print()
    if remove_claude_md:
        claude_md_dst.unlink()
        print(f"[OK] Removed {claude_md_dst}")
    else:
        print(f"[--] Skipped {claude_md_dst} (not a managed symlink)")

    # --- 6. Remove MCP servers from ~/.claude.json ---
    print()
    if managed_servers:
        print(f"Removing {len(managed_servers)} MCP server(s) from {_CLAUDE_JSON}:")
        _remove_mcp_from_user_scope(managed_servers)
    else:
        print(f"  [--] No managed MCP servers to remove from {_CLAUDE_JSON}")

    # --- 7. Uninstall CLI ---
    print()
    _uninstall_cli_tool()

    # --- Done ---
    print()
    print("Uninstall complete.")
    print()
    print(f"Note: {AGENTIHOOKS_STATE_DIR}/ was NOT removed (your data).")
    print(f"      .env    : {_ENV_FILE_DST}")
    print(f"      state   : {STATE_JSON}")
    print(f"      Full reset: rm -rf {AGENTIHOOKS_STATE_DIR}")


# ---------------------------------------------------------------------------
# Project install
# ---------------------------------------------------------------------------


def install_project(args: argparse.Namespace) -> None:
    project_path = Path(args.path).expanduser().resolve()
    profile_name = args.profile

    if not project_path.exists():
        print(f"ERROR: Project path does not exist: {project_path}", file=sys.stderr)
        sys.exit(1)
    if not project_path.is_dir():
        print(
            f"ERROR: Project path is not a directory: {project_path}", file=sys.stderr
        )
        sys.exit(1)

    # Validate profile
    profile_dir = PROFILES_DIR / profile_name
    if not profile_dir.is_dir():
        available = _available_profiles()
        print(f"ERROR: Profile '{profile_name}' not found.", file=sys.stderr)
        print(f"Available profiles: {', '.join(available)}", file=sys.stderr)
        sys.exit(1)

    mcp_categories = _read_profile_field(profile_dir, "mcp_categories") or "all"
    rendered_mcp = _build_mcp_config(mcp_categories)

    mcp_dst = project_path / _MCP_JSON_NAME
    if mcp_dst.exists():
        answer = (
            input(f"{_MCP_JSON_NAME} already exists at {mcp_dst}. Overwrite? [y/N] ")
            .strip()
            .lower()
        )
        if answer != "y":
            print("Aborted.")
            sys.exit(0)

    save_json(mcp_dst, rendered_mcp)
    print(f"[OK] Wrote {mcp_dst}")
    print()
    print(
        f"Next: open Claude Code in '{project_path}' and run /mcp to verify the hooks-utils server."
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _scan_mcp_dir(scan_dir: Path) -> list[tuple[Path, dict]]:
    """Scan *scan_dir* for JSON files containing ``mcpServers``.

    Returns a sorted list of (path, servers_dict) tuples.
    """
    results: list[tuple[Path, dict]] = []
    if not scan_dir.is_dir():
        return results
    for f in sorted(scan_dir.glob("*.json")):
        try:
            data = load_json(f)
            if "mcpServers" in data and data["mcpServers"]:
                results.append((f, data["mcpServers"]))
        except (json.JSONDecodeError, OSError):
            pass
    # Also check hidden .json files (e.g., .anton-mcp.json)
    for f in sorted(scan_dir.glob(".*.json")):
        try:
            data = load_json(f)
            if "mcpServers" in data and data["mcpServers"]:
                results.append((f, data["mcpServers"]))
        except (json.JSONDecodeError, OSError):
            pass
    # Deduplicate by path (glob patterns may overlap)
    seen: set[str] = set()
    deduped: list[tuple[Path, dict]] = []
    for fpath, servers in results:
        key = str(fpath)
        if key not in seen:
            seen.add(key)
            deduped.append((fpath, servers))
    return deduped


def _find_companion_env(mcp_file: Path) -> Path | None:
    """Find a companion .env file for an MCP JSON file.

    Checks for: anton-mcp.env, anton.env (from anton-mcp.json).
    """
    stem = mcp_file.stem  # e.g. "anton-mcp"
    for candidate_name in [f"{stem}.env", f"{stem.removesuffix('-mcp')}.env"]:
        candidate = mcp_file.parent / candidate_name
        if candidate.is_file():
            return candidate
    return None


def _display_mcp_list(mcp_files: list[tuple[Path, dict]], tracked: set[str]) -> None:
    """Print a numbered list of MCP files; servers shown as bullet points."""
    for i, (f, servers) in enumerate(mcp_files, 1):
        marker = f"  \033[32m[installed]\033[0m" if str(f) in tracked else ""
        print(f"  {i}. {f.name}{marker}")
        for name in servers:
            print(f"     \033[2m•\033[0m {name}")
        env_file = _find_companion_env(f)
        if env_file:
            print(f"     \033[2menv: {env_file.name}\033[0m")


def _prompt_server_selection(servers: dict, action: str = "install") -> dict | None:
    """Stage-2 prompt: pick individual servers or all from *servers*.

    Returns a ``{name: config}`` subset, or ``None`` if the user aborted.
    Accepts:
      0          — all servers
      1          — single server by number
      1,3        — comma-separated selection
    """
    names = list(servers.keys())
    print(f"  0. All ({len(names)} server{'s' if len(names) != 1 else ''})")
    for i, name in enumerate(names, 1):
        print(f"  {i}. {name}")
    print()
    if len(names) == 1:
        try:
            raw = input(f"{action.capitalize()} {names[0]}? [Y/n]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            return None
        return None if raw in ("n", "no") else servers
    try:
        raw = input(
            f"Select (0=all, 1-{len(names)}, or comma list): "
        ).strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        return None
    if not raw or raw.lower() == "q":
        print("Aborted.")
        return None
    if raw == "0":
        return servers
    try:
        selected: dict = {}
        for part in raw.split(","):
            idx = int(part.strip()) - 1
            if not 0 <= idx < len(names):
                raise ValueError(f"{idx + 1}")
            selected[names[idx]] = servers[names[idx]]
        return selected
    except ValueError as exc:
        print(f"Invalid selection: {exc}")
        return None


def cmd_mcp_action(
    action: str, scan_dir: Path | None = None, *, mcp_path: Path | None = None
) -> None:
    """Handle ``agentihooks mcp list|install|uninstall|sync|add``.

    *scan_dir* defaults to ``~/.agentihooks/``.
    """
    if scan_dir is None:
        scan_dir = AGENTIHOOKS_STATE_DIR

    tracked = set(_load_state().get("mcpFiles", []))

    if action == "list":
        mcp_files = _scan_mcp_dir(scan_dir)
        if not mcp_files:
            print(f"No MCP files found in {scan_dir}")
            print(f"\nDrop .json files with a mcpServers key into {scan_dir}")
            return
        print(f"MCP files in {scan_dir}:\n")
        _display_mcp_list(mcp_files, tracked)
        if tracked:
            print(f"\nCurrently installed: {len(tracked)} file(s)")
        print(f"\nTo install:   agentihooks mcp install")
        print(f"To uninstall: agentihooks mcp uninstall")

    elif action == "install":
        mcp_files = _scan_mcp_dir(scan_dir)
        if not mcp_files:
            print(f"No MCP files found in {scan_dir}")
            print(f"\nDrop .json files with a mcpServers key into {scan_dir}")
            return
        # Stage 1 — pick a file
        if len(mcp_files) == 1:
            selected_file, all_servers = mcp_files[0]
            print(f"{selected_file.name}\n")
            for name in all_servers:
                print(f"  \033[2m•\033[0m {name}")
        else:
            print(f"MCP files in {scan_dir}:\n")
            _display_mcp_list(mcp_files, tracked)
            print()
            try:
                raw = input(
                    f"Enter file number (1-{len(mcp_files)}, or q to quit): "
                ).strip()
            except (EOFError, KeyboardInterrupt):
                print("\nAborted.")
                sys.exit(0)
            if raw.lower() == "q":
                print("Aborted.")
                return
            try:
                idx = int(raw) - 1
                if not 0 <= idx < len(mcp_files):
                    raise ValueError
            except ValueError:
                print("Invalid selection.")
                sys.exit(1)
            selected_file, all_servers = mcp_files[idx]
        # Stage 2 — pick server(s) from the file
        print(f"\nServers in {selected_file.name}:\n")
        selected_servers = _prompt_server_selection(all_servers)
        if selected_servers is None:
            return
        print()
        _merge_mcp_to_user_scope(selected_servers)
        _state_add_mcp(selected_file)
        print("  Restart Claude Code for the changes to take effect.")

    elif action == "uninstall":
        if not tracked:
            print("No MCP files currently installed — nothing to uninstall.")
            return
        # Build list of installed files with their server dicts
        installed: list[tuple[Path, dict]] = []
        for path_str in sorted(tracked):
            p = Path(path_str)
            if not p.exists():
                installed.append((p, {}))
                continue
            try:
                data = load_json(p)
                installed.append((p, data.get("mcpServers", {})))
            except (json.JSONDecodeError, OSError):
                installed.append((p, {}))
        # Stage 1 — pick a file
        if len(installed) == 1:
            selected_file, all_servers = installed[0]
            print(f"{selected_file.name}\n")
            for name in all_servers:
                print(f"  \033[2m•\033[0m {name}")
        else:
            print("Installed MCP files:\n")
            _display_mcp_list(installed, tracked)
            print()
            try:
                raw = input(
                    f"Enter file number (1-{len(installed)}, or q to quit): "
                ).strip()
            except (EOFError, KeyboardInterrupt):
                print("\nAborted.")
                sys.exit(0)
            if raw.lower() == "q":
                print("Aborted.")
                return
            try:
                idx = int(raw) - 1
                if not 0 <= idx < len(installed):
                    raise ValueError
            except ValueError:
                print("Invalid selection.")
                sys.exit(1)
            selected_file, all_servers = installed[idx]
        if not all_servers:
            print(f"  [!!] Cannot read servers from {selected_file} — removing from tracking.")
            _state_remove_mcp(selected_file)
            return
        # Stage 2 — pick server(s) to remove
        print(f"\nServers in {selected_file.name}:\n")
        selected_servers = _prompt_server_selection(all_servers, action="uninstall")
        if selected_servers is None:
            return
        print()
        _remove_mcp_from_user_scope(selected_servers)
        # Remove file from state only if all its servers were uninstalled
        if set(selected_servers.keys()) >= set(all_servers.keys()):
            _state_remove_mcp(selected_file)
        print("  Restart Claude Code for the changes to take effect.")

    elif action == "sync":
        sync_user_mcp()

    elif action == "add":
        if mcp_path is None:
            print("Usage: agentihooks mcp add <path>")
            sys.exit(1)
        manage_user_mcp(mcp_path)
        print("\nRestart Claude Code for the changes to take effect.")

    else:
        print(f"Unknown action: {action}")
        print("Usage: agentihooks mcp [list|install|uninstall|sync|add]")
        sys.exit(1)


def cmd_ignore(target_dir: Path, *, force: bool = False) -> None:
    """Create a .claudeignore in *target_dir* (defaults to cwd).

    If the file already exists it is left untouched unless --force is passed,
    in which case it is overwritten with a fresh copy of the template.
    """
    dest = target_dir / ".claudeignore"

    if dest.exists() and not force:
        print(f"  [--] {dest} already exists — use --force to overwrite")
        return

    action = "Overwrote" if dest.exists() else "Created"
    dest.write_text(CLAUDEIGNORE_TEMPLATE, encoding="utf-8")
    print(f"  [OK] {action} {dest}")
    print(f"       Edit it to add project-specific exclusions.")


def cmd_quota(args: "argparse.Namespace") -> None:
    """Launch or interact with the Claude.ai quota watcher."""
    watcher = AGENTIHOOKS_ROOT / "scripts" / "claude_usage_watcher.py"
    if not watcher.exists():
        print(f"ERROR: quota watcher not found at {watcher}", file=sys.stderr)
        sys.exit(1)

    python = str(_detect_venv() or sys.executable)

    if args.action == "import-cookies":
        os.execv(python, [python, str(watcher), "--import-cookies"])

    elif args.action == "status":
        import json as _json
        usage_file = Path(os.getenv("CLAUDE_USAGE_FILE", str(Path.home() / ".agentihooks" / "claude_usage.json")))
        if not usage_file.exists():
            print("No quota data yet. Run:  agentihooks quota")
            sys.exit(0)
        data = _json.loads(usage_file.read_text())
        print(_json.dumps(data, indent=2))

    else:  # watch (default)
        cmd = [python, str(watcher)]
        if args.headless:
            cmd.append("--headless")
        if getattr(args, "chromium", False):
            cmd.append("--chromium")
        if args.poll != 60:
            cmd += ["--poll", str(args.poll)]
        os.execv(python, cmd)


def main() -> None:
    # Split argv on '--' so everything after it becomes the exec command.
    _argv = sys.argv[1:]
    _sep = _argv.index("--") if "--" in _argv else None
    _exec_cmd: list[str] = _argv[_sep + 1 :] if _sep is not None else []
    _argv = _argv[:_sep] if _sep is not None else _argv

    parser = argparse.ArgumentParser(
        description="Install agentihooks settings/hooks/skills/agents to ~/.claude or a project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=_USAGE_TEXT,
    )
    parser.add_argument(
        "--list-profiles",
        action="store_true",
        help="List available profiles and exit",
    )
    parser.add_argument(
        "--query",
        action="store_true",
        help="Print the currently active global profile name and exit",
    )
    parser.add_argument(
        "--loadenv",
        nargs="?",
        const="",
        metavar="PATH",
        help="Install agentienv alias into ~/.bashrc and offer to install requirements.txt",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="With --loadenv: install requirements into system Python (for Docker/CI, skips venv check)",
    )
    sub = parser.add_subparsers(dest="command")

    glob_p = sub.add_parser(
        "global", help="Install hooks + skills + agents into ~/.claude"
    )
    glob_p.add_argument(
        "--profile",
        default=os.environ.get("AGENTIHOOKS_PROFILE", "default"),
        help=f"Profile whose CLAUDE.md to link (default: 'default', env: AGENTIHOOKS_PROFILE). Available: {', '.join(_available_profiles())}",
    )

    proj = sub.add_parser(
        "project", help="Install a profile's .mcp.json into a target project"
    )
    proj.add_argument("path", help="Target project directory")
    proj.add_argument(
        "--profile",
        default=os.environ.get("AGENTIHOOKS_PROFILE", "default"),
        help="Profile to use (default: 'default', env: AGENTIHOOKS_PROFILE)",
    )

    unsub = sub.add_parser(
        "uninstall", help="Remove all agentihooks artifacts from the system"
    )
    unsub.add_argument(
        "--yes", "-y", action="store_true", help="Skip confirmation prompt"
    )

    mcp_p = sub.add_parser(
        "mcp",
        help="Manage MCP server files (list, install, uninstall, sync, add)",
    )
    mcp_p.add_argument(
        "action",
        nargs="?",
        default="list",
        choices=["list", "install", "uninstall", "sync", "add"],
        help="Action to perform (default: list)",
    )
    mcp_p.add_argument(
        "mcp_path",
        nargs="?",
        default=None,
        help="Path to MCP file (only used with 'add' action)",
    )
    mcp_p.add_argument(
        "--dir",
        default=None,
        help=f"Directory to scan for MCP files (default: {AGENTIHOOKS_STATE_DIR})",
    )

    ign_p = sub.add_parser(
        "ignore", help="Create a .claudeignore in the current directory"
    )
    ign_p.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Target directory (default: current directory)",
    )
    ign_p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing .claudeignore",
    )

    quota_p = sub.add_parser(
        "quota",
        help="Manage the Claude.ai console quota watcher",
    )
    quota_p.add_argument(
        "action",
        nargs="?",
        default="watch",
        choices=["watch", "import-cookies", "status"],
        help="watch (default) — open browser and start watcher; import-cookies — paste sessionKey cookie; status — print last known quota",
    )
    quota_p.add_argument("--headless", action="store_true", help="Run headless using bundled Chromium (no window, for background daemon)")
    quota_p.add_argument("--chromium", action="store_true", help="Force Playwright's bundled Chromium instead of Windows Chrome")
    quota_p.add_argument("--poll", type=int, default=60, help="Poll interval in seconds (default: 60)")

    args = parser.parse_args(_argv)

    if args.loadenv is not None:
        _cmd_loadenv(
            Path(args.loadenv).expanduser() if args.loadenv else _ENV_FILE_DST,
            _exec_cmd,
            force=args.force,
        )
        return

    if args.list_profiles:
        list_profiles()
        return

    if args.query:
        query_active_profile()
        return

    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "global":
        install_global(args)
    elif args.command == "project":
        install_project(args)
    elif args.command == "uninstall":
        uninstall_global(args)
    elif args.command == "mcp":
        scan_dir = Path(args.dir).expanduser().resolve() if args.dir else None
        mcp_path = Path(args.mcp_path).expanduser().resolve() if args.mcp_path else None
        cmd_mcp_action(args.action, scan_dir, mcp_path=mcp_path)
    elif args.command == "ignore":
        cmd_ignore(Path(args.path).expanduser().resolve(), force=args.force)
    elif args.command == "quota":
        cmd_quota(args)


if __name__ == "__main__":
    main()
